### ISSUE TITLE
Fine tuning code? 

### ISSUE THREAD

**Issue by rambalachandran** [aiola-lab/whisper-ner#5]
This is a wonderful work and is there any way to get the fine tuning code? I'm looking to fine tune NER for some core engineering entity names. Thanks in advance

**Comment by AvivNavon** [comment]
Hi @rambalachandran, thanks for showing interest in our work.
Yes, we plan on releasing the training code in the near future. Will update here.

**Comment by rambalachandran** [comment]
Thank you. Will look out for updates here

**Comment by AvivNavon** [comment]
Hi @jugal-sheth, currently we only trained and released the large Whisper variant. We plan on releasing the training code in the coming days, to allow others to finetune the model or train other variants.

**Comment by AvivNavon** [comment]
Hi, the training code is now available 🥳

**Comment by jugal-sheth** [comment]
@AvivNavon Thank you so much
